# Arrays, Matrices & Tensors

Arrays are the most powerful and useful features in Julia. Let's start with some basics. 

In [1]:
students = ["jack", "jill", "john"]

3-element Array{String,1}:
 "jack"
 "jill"
 "john"

In [2]:
typeof(students)

Array{String,1}

String defines the type of the elements and 1 is the dimension of the array. So, this is a **"1D array of string values"**.

In [3]:
fib = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [4]:
typeof(fib)

Array{Int64,1}

In [5]:
push!(fib, 21)

8-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21

In [6]:
@show fib; 

fib = [1, 1, 2, 3, 5, 8, 13, 21]


In [7]:
pop!(fib)

21

In [8]:
@show fib;

fib = [1, 1, 2, 3, 5, 8, 13]


## 2D Arrays

In [11]:
mat = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9, 24]
]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]
 [7, 8, 9, 24]

In [12]:
typeof(mat)

Array{Array{Int64,1},1}

Notice the type! It's not a 2D matrix. It's a 1D array but each element within it is a 1D array itself! These are useful in certain cases, but we are usually interested in 2D arrays in data science and machine learning.

Let's create a 2D array. 

## Matrices 

In [13]:
x = [1 2 3]       # notice the lack of commas (and the dimensions) 

1×3 Array{Int64,2}:
 1  2  3

In [14]:
x'                # turn this into a column vector 

3×1 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1
 2
 3

In [22]:
mat = [
       [1  2  3] 
       [4  5  6] 
       [7  8  9]
      ]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [23]:
typeof(mat)

Array{Int64,2}

### Sizes (Shapes) and Reshaping 

In [24]:
size(mat)     # extremely important in modern machine learning 

(3, 3)

In [25]:
size(x)

(1, 3)

In [26]:
size(fib)     # Important difference 

(7,)

In [27]:
X = [
       [1   2   3] 
       [4   5   6] 
       [7   8   9]
       [10  11  12]
      ]

4×3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [28]:
X = reshape(X, 2, 6)

2×6 Array{Int64,2}:
 1   7  2   8  3   9
 4  10  5  11  6  12

In [29]:
X = reshape(X, 12, 1)

12×1 Array{Int64,2}:
  1
  4
  7
 10
  2
  5
  8
 11
  3
  6
  9
 12

In [31]:
X = reshape(X, 4, 3)

4×3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

## Helper Functions 

### Creating Random Matrices

In [32]:
rand(4, 3)

4×3 Array{Float64,2}:
 0.192271  0.902721  0.431684
 0.978904  0.326399  0.66349
 0.184517  0.912208  0.604661
 0.651662  0.799301  0.040425

In [33]:
mat = rand(4, 3)

4×3 Array{Float64,2}:
 0.907329  0.686946  0.0433964
 0.25102   0.271209  0.436602
 0.833106  0.362261  0.493701
 0.305279  0.625281  0.295096

In [34]:
mat_2 = mat;

In [35]:
mat_2[1, 1] = 100.0

100.0

In [36]:
mat_2

4×3 Array{Float64,2}:
 100.0       0.686946  0.0433964
   0.25102   0.271209  0.436602
   0.833106  0.362261  0.493701
   0.305279  0.625281  0.295096

In [37]:
mat

4×3 Array{Float64,2}:
 100.0       0.686946  0.0433964
   0.25102   0.271209  0.436602
   0.833106  0.362261  0.493701
   0.305279  0.625281  0.295096

### Copying Arrays 

In [38]:
mat_3 = copy(mat)  
# this creates a copy of the values 

4×3 Array{Float64,2}:
 100.0       0.686946  0.0433964
   0.25102   0.271209  0.436602
   0.833106  0.362261  0.493701
   0.305279  0.625281  0.295096

In [39]:
mat_3[1, 1] = 999.0

999.0

In [40]:
mat

4×3 Array{Float64,2}:
 100.0       0.686946  0.0433964
   0.25102   0.271209  0.436602
   0.833106  0.362261  0.493701
   0.305279  0.625281  0.295096

In [41]:
mat_3

4×3 Array{Float64,2}:
 999.0       0.686946  0.0433964
   0.25102   0.271209  0.436602
   0.833106  0.362261  0.493701
   0.305279  0.625281  0.295096

## Comprehensions 

We can also do nested loops with comprehensions. 

In [44]:
[i^2 for i in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [45]:
[(i, j) for i in 1:5, j in 6:10]      # cartesian product (or nested loop)

5×5 Array{Tuple{Int64,Int64},2}:
 (1, 6)  (1, 7)  (1, 8)  (1, 9)  (1, 10)
 (2, 6)  (2, 7)  (2, 8)  (2, 9)  (2, 10)
 (3, 6)  (3, 7)  (3, 8)  (3, 9)  (3, 10)
 (4, 6)  (4, 7)  (4, 8)  (4, 9)  (4, 10)
 (5, 6)  (5, 7)  (5, 8)  (5, 9)  (5, 10)

In [48]:
[(i^2, j+1//2) for i in 1:5, j in 6:10]

5×5 Array{Tuple{Int64,Rational{Int64}},2}:
 (1, 13//2)   (1, 15//2)   (1, 17//2)   (1, 19//2)   (1, 21//2)
 (4, 13//2)   (4, 15//2)   (4, 17//2)   (4, 19//2)   (4, 21//2)
 (9, 13//2)   (9, 15//2)   (9, 17//2)   (9, 19//2)   (9, 21//2)
 (16, 13//2)  (16, 15//2)  (16, 17//2)  (16, 19//2)  (16, 21//2)
 (25, 13//2)  (25, 15//2)  (25, 17//2)  (25, 19//2)  (25, 21//2)

## Matrix Operations 

In [49]:
A = rand(10:20, 3, 3)


# 3x3 matrix with each value between 10 and 20 

3×3 Array{Int64,2}:
 15  16  19
 10  11  13
 10  16  18

In [50]:
A = rand(10.:20, 3, 3) 
# Changing the range changes the type to Float64

3×3 Array{Float64,2}:
 10.0  15.0  12.0
 18.0  17.0  16.0
 18.0  10.0  10.0

Instead of random values, we can provide a specific value using the fill method. 

In [51]:
x = fill(10.0, (3, ))

3-element Array{Float64,1}:
 10.0
 10.0
 10.0

In [52]:
A*x 
# this is the usual matrix-vector multiplication 
# of course, this requires a 'size match'

3-element Array{Float64,1}:
 370.0
 510.0
 380.0

### Transpose, Trace, Determinant

In [53]:
A'

3×3 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 10.0  18.0  18.0
 15.0  17.0  10.0
 12.0  16.0  10.0

In [54]:
A' * A

3×3 Array{Float64,2}:
 748.0  636.0  588.0
 636.0  614.0  552.0
 588.0  552.0  500.0

In [55]:
A'A      # shortcut ... typical with Julia 

3×3 Array{Float64,2}:
 748.0  636.0  588.0
 636.0  614.0  552.0
 588.0  552.0  500.0

In [58]:
tr(A)     # the trace of A 

37.0

In [57]:
using LinearAlgebra

In [60]:
det(A)    # determinant needs the LinearAlgebra package 

208.00000000000017

In [61]:
inv(A)

3×3 Array{Float64,2}:
  0.0480769  -0.144231   0.173077
  0.519231   -0.557692   0.269231
 -0.605769    0.817308  -0.480769

## Solving Linear Equations Directly 

In [62]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.488533    0.492501  0.982323
 0.066644    0.495637  0.486983
 0.00134901  0.464733  0.0322481

In [63]:
x

3-element Array{Float64,1}:
 10.0
 10.0
 10.0

In [64]:
b = A*x

3-element Array{Float64,1}:
 19.633568748304175
 10.492637889309762
  4.983298643938216

In [65]:
A\b  # Solve for b 

3-element Array{Float64,1}:
  9.999999999999993
  9.999999999999998
 10.000000000000005

## More ... 

We can create n-dim arrays easily too. These tensors will come in handy when we get to machine learning.  

In [67]:
rand(4, 3, 2, 5)

4×3×2×5 Array{Float64,4}:
[:, :, 1, 1] =
 0.423244  0.0352447  0.774295
 0.489153  0.785294   0.172679
 0.388045  0.977007   0.0229555
 0.344082  0.542838   0.473859

[:, :, 2, 1] =
 0.745864  0.193607  0.238217
 0.330387  0.93698   0.565352
 0.283217  0.539425  0.072358
 0.402641  0.787651  0.124508

[:, :, 1, 2] =
 0.672048  0.246398  0.829686
 0.148401  0.947259  0.212136
 0.255381  0.657003  0.804505
 0.238833  0.827475  0.29062

[:, :, 2, 2] =
 0.367693  0.102804  0.163404
 0.78897   0.968477  0.0506917
 0.806755  0.605732  0.487859
 0.131589  0.222102  0.928187

[:, :, 1, 3] =
 0.452051  0.809278  0.274124
 0.875623  0.157866  0.740942
 0.542228  0.781493  0.0584045
 0.311778  0.501798  0.586056

[:, :, 2, 3] =
 0.281244   0.274081  0.365858
 0.123989   0.251427  0.934947
 0.40397    0.85127   0.851383
 0.0800254  0.327581  0.444562

[:, :, 1, 4] =
 0.102543  0.700775  0.69672
 0.979993  0.835484  0.5031
 0.582695  0.23989   0.698904
 0.470617  0.935795  0.307495

[:, :, 2, 4] =


More operations can be seen in the LinearAlgebra package. https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/

We will get to these if and when we need more. 