# Interfacing with Other Languages 

## Calling Python Builtins and Custom Code

First, let's install the package needed to interface with Python code. We give this as a **package mode** command. 

In [ ]:
] add PyCall

In [ ]:
using PyCall

In [ ]:
math = pyimport("math")
math.sin(math.pi / 4)

In [ ]:
math.sqrt(36)

In [ ]:
push!(pyimport("sys")["path"], pwd());

In [ ]:
pyex = pyimport("pyex")

In [ ]:
pyex.sqrt(36)

In [ ]:
pyimport("importlib")."reload"(pyex) # if you change something in python module, you have to reload it

In [ ]:
pyex.sqrt(36)

## Calling R

I don't have R installed on my machine but if you do, you can run this simple example to see how you can call R operations from within Julia. 

In [ ]:
] add RCall

In [ ]:
using RCall

In [1]:
X = randn(3,2)
b = reshape([2.0, 3.0], 2,1)
y = X * b + randn(3,1)

3×1 Array{Float64,2}:
  6.31203894396598
 -1.733433607576226
  0.7197381393982236

In [2]:
X

3×2 Array{Float64,2}:
 1.27435    0.861433
 0.376687  -0.839999
 1.83388   -0.990183

In [3]:
b

2×1 Array{Float64,2}:
 2.0
 3.0

In [4]:
y

3×1 Array{Float64,2}:
  6.31203894396598
 -1.733433607576226
  0.7197381393982236

In [ ]:
@rput y
@rput X

In [ ]:
R"z <- y * 3"    # do something in R 

In [ ]:
@rget z
@show z      # z should now be available in Julia 