# Basic Functional Programming 

Functional programming is very useful when thinking in terms of mathematics. It's also massively parallelizable and you really should learn the concepts. Here, we will take a look at some basics. 

## Map 

Map applies a function to all elements of a collection. 

In [1]:
collection = [1, 2, 4]

3-element Array{Int64,1}:
 1
 2
 4

In [2]:
map(x -> x^2, collection)

3-element Array{Int64,1}:
  1
  4
 16

In [3]:
squares = map(x -> x^2, collection);

In [4]:
@show squares;

squares = [1, 4, 16]


`map` is, therefore, a **higher-order function** since it takes in a function as it's argument. Functional programming revolves around this very concept. It's very useful since, as you can see, it can be parallelized. There are complete algorithms that solve many common problems using functional programming concepts such as `map`, `reduce` and `filter`. 

## Reduce 


In [7]:
collection = [1, 2, 4, 10]

4-element Array{Int64,1}:
  1
  2
  4
 10

In [8]:
reduce(+, collection)  # applies the function to first two elements, then result+3rd_element and so on ...  

17

We will leave the rest of this for you to explore when you need this. We need to move to something much more relevant to Julia and our course of action. 

## Broadcast 

Let's see this with an example. 

In [9]:
collection = [1, 2, 4]

3-element Array{Int64,1}:
 1
 2
 4

In [10]:
function f(x) 
    x ^ 2 
end

f (generic function with 1 method)

In [11]:
broadcast(f, collection)      # seems similar to map 

3-element Array{Int64,1}:
  1
  4
 16

In [12]:
collection

3-element Array{Int64,1}:
 1
 2
 4

In [13]:
f.(collection)   # it's so useful, it has a shortcut 

3-element Array{Int64,1}:
  1
  4
 16

In [14]:
f(collection)     # this does not work because you can't square an array 

LoadError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float32, ::Integer) at math.jl:907
  ^(!Matched::Float16, ::Integer) at math.jl:915
  ^(!Matched::Regex, ::Integer) at regex.jl:729
  ...

Let's see how a broadcast call is different from a normal call. 

In [15]:
m = ones(3, 3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [16]:
f(m)      # this is m^2, which is m*m 

3×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [17]:
f.(m)     # this applies x^2 to each element separately! 

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [18]:
A = [
     [1 2 3]
     [4 5 6]
     [7 8 9]
    ]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [19]:
A .+ 1     # apply +1 to each element separately 

3×3 Array{Int64,2}:
 2  3   4
 5  6   7
 8  9  10

In [20]:
A .* 2 

3×3 Array{Int64,2}:
  2   4   6
  8  10  12
 14  16  18

In [21]:
# or even ... 
2A   

3×3 Array{Int64,2}:
  2   4   6
  8  10  12
 14  16  18

In [ ]:
f.(2A) # we can write stuff that is closer to the maths this way! 

This comes up again and again in Julia's practice. 

### Broadcasting for Matrices 

In [22]:
A = [
    [1 2 3]
    [4 5 6]
    ]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [23]:
# Without broadcasting 
A * [10 20 30]             # works if you transpose but that's a different operation

LoadError: DimensionMismatch("matrix A has dimensions (2,3), matrix B has dimensions (1,3)")

In [31]:
A = [
    [1  2  3]
    [4  5  6]
    ];

In [29]:
# With broadcasting 

A .* [10 20 30]          # row vector is duplicated for each row 

3×3 Array{Int64,2}:
 10   40   90
 40  100  180
 50  160  210

In [32]:
A .* [10 20]'            # column vector is duplicated for each column 

2×3 Array{Int64,2}:
 10   20   30
 80  100  120